version: "2"

run:
  tests: false

linters:
  default: all
  disable:
    - wrapcheck
    - varnamelen
    - revive
    - mnd
    - lll
    - ireturn
    - gocognit
    - gochecknoglobals
    - funlen
    - forcetypeassert
    - exhaustive
    - err113
    - cyclop

  exclusions:
    paths-except:
      - main.go
