version: "2"

run:
  tests: false

linters:
  default: all
  disable:
    - wrapcheck
    - varnamelen
    - revive
    - mnd
    - ireturn
    - err113
    - exhaustive
    - lll
    - cyclop
    - funlen

  exclusions:
    paths-except:
      - main.go
